version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_new
    environment:
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: newpass123
      POSTGRES_DB: newdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: api-shopper-gemini-container-new
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=postgres
      - DB_USER=newuser
      - DB_PASSWORD=newpass123
      - DB_NAME=newdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
